# Generated by Django 5.2.14 on 2026-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64, null=True)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in writing', 'in writing'), ('pending editor approval', 'pending editor approval'), ('published', 'published')], default='in writing', max_length=50)),
                ('publish_date', models.DateField(null=True)),
                ('removal_date', models.DateField(null=True)),
            ],
        ),
    ]
