# Generated by Django 5.2.14 on 2026-05-24 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0004_album_alter_article_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_1.band'),
            preserve_default=False,
        ),
    ]
