# Generated by Django 5.2.14 on 2026-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0006_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='django_1.category'),
        ),
    ]
